# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [4]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [10]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [11]:
np.random.random(1)

array([0.87762862])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
b = np.random.standard_normal(25)
b.mean()
b.std()
b

array([-1.31584871, -0.3894213 ,  0.40331058, -1.67886509,  1.66807912,
       -0.6724826 ,  0.41127654,  1.28429583, -0.17004616, -1.13605394,
       -0.09068067, -0.15466083,  1.83250838,  0.6699805 ,  0.48087295,
        0.55073518,  0.89347317,  0.1946666 ,  0.26827292, -1.1168707 ,
       -1.23761675, -1.39184924,  0.04231762,  1.35153315, -1.05144539])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [17]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Create the following 2D matrix. 

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

#### Get the sum of all the values in matrix

#### Get the standard deviation of the values in matrix

#### Get the sum of all the columns in matrix