# NumPy Exercises



#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [22]:
import numpy as np
np.full(10, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create an array of 10 fives



In [7]:
import numpy as np
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [5]:
import numpy as np
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np. arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [17]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Use NumPy to generate a random number between 0 and 1

In [23]:
np.random.random((1,1))

array([[0.23754061]])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:
np.random.randn(25)

array([ 0.62870342,  1.19677838, -1.59222029,  0.10342863,  1.68093999,
        0.68314853, -1.37466699,  1.08921379,  1.14569361, -1.5651847 ,
        0.14234574,  1.4717529 , -0.5047758 ,  0.39507003, -1.0962591 ,
        1.15694472,  0.33703363, -0.0967958 ,  0.89004556, -0.55229578,
       -1.08699718,  0.22390917,  1.21225029, -0.77081067, -1.66403277])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Create the following 2D matrix.

[ 1,  2,  3,  4,  5]
[ 6,  7,  8,  9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 25]

Number of elements: 40


#### Get the sum of all the values in matrix

In [31]:
import numpy as np

# Create a 1D array with values from -100 to 100
array_values = np.arange(-100, 101)

# Compute the average score
average_score = np.mean(array_values)

# Compute the standard deviation
std_deviation = np.std(array_values)

print("Average Score:", average_score)
print("Standard Deviation:", std_deviation)


Average Score: 0.0
Standard Deviation: 58.02298395176403


#### Get the standard deviation of the values in matrix

#### Get the sum of all the columns in matrix